version: "2.0"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./backend/.env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=todo-user
      - MONGO_INITDB_ROOT_PASSWORD=w3rvNEgfKRz2NEl7
    volumes:
      - /data/db
    networks:
      - todo-net
  frontend:
    build: ./frontend
    image: todo-frontend
    container_name: todo-frontend-container
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo-net
    depends_on:
      - backend
  backend:
    build: ./backend
    image: todo-backend
    container_name: todo-backend-container
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=mongodb://todo-user:w3rvNEgfKRz2NEl7@mongo:27017/todo-project?authSource=admin
      - TEST_DATABASE_URL=mongodb://todo-user:w3rvNEgfKRz2NEl7@mongo:27017/todo-test?authSource=admin
      - JWT_SECRET=never_gonna_give_you_up
      - JWT_EXPIRES_IN=7d
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo-net
networks:
  todo-net:
    driver: bridge
