version: "2.0"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./backend/.env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=todo-user
      - MONGO_INITDB_ROOT_PASSWORD=w3rvNEgfKRz2NEl7
    volumes:
      - /data/db
      # - ./backend/configs/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - todo-net
  frontend:
    build: ./frontend
    image: todo-frontend
    container_name: todo-frontend-container
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo-net
    depends_on:
      - backend
  backend:
    build: ./backend
    image: todo-backend
    container_name: todo-backend-container
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo-net
networks:
  todo-net:
    driver: bridge
