version: "2.0"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=todo-user
      - MONGO_INITDB_ROOT_PASSWORD=w3rvNEgfKRz2NEl7
    volumes:
      - /data/db
    networks:
      - todo-net
  frontend:
    build: ./frontend
    image: todo-frontend
    container_name: todo-frontend-container
    ports:
      - "5173:5173"
    environment:
      - VITE_USER_SERVICE_URL=http://localhost:5000
      - VITE_TODO_SERVICE_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo-net
    depends_on:
      - user-service
      - todo-service
  user-service:
    build: ./backend/user-service
    image: user-service
    container_name: user-container
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/todo-project
      - TEST_DATABASE_URL=mongodb://mongo:27017/todo-test
      - JWT_SECRET=never_gonna_give_you_up
      - JWT_EXPIRES_IN=86400
    volumes:
      - ./backend/user-service:/user-service/app
      - /user-service/app/node_modules
    networks:
      - todo-net
  todo-service:
    build: ./backend/todo-service
    image: todo-service
    container_name: todo-container
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/todo-project
      - TEST_DATABASE_URL=mongodb://mongo:27017/todo-test
      - JWT_SECRET=never_gonna_give_you_up
      - JWT_EXPIRES_IN=86400
    volumes:
      - ./backend/todo-service:/todo-service/app
      - /todo-service/app/node_modules
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
