version: '2.0'

services:
  frontend:
    build: ./frontend
    image: todo-frontend
    container_name: todo-frontend-container
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo-net
    depends_on:
      - backend
  backend:
    build: ./backend
    image: todo-backend
    container_name: todo-backend-container
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb+srv://todo-user:w3rvNEgfKRz2NEl7@cluster0.depajlm.mongodb.net/todo-project
      - JWT_SECRET=never_gonna_give_you_up
      - JWT_EXPIRES_IN = 86400
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge